"""
report.py

Professional report generator for the Claus SOC Toolkit.

Generates:
- HTML Reports
- Text Reports
"""

from datetime import datetime
from pathlib import Path

from jinja2 import Environment, FileSystemLoader

from config import (
    APP_NAME,
    APP_VERSION,
    AUTHOR,
    TEMPLATE_DIR,
    HTML_REPORT,
)

from logger import logger


class ReportGenerator:
    """
    Generates professional SOC reports.
    """

    def __init__(self, results):

        self.results = results

        self.generated = datetime.now()

        self.environment = Environment(
            loader=FileSystemLoader(TEMPLATE_DIR)
        )

    # =====================================================
    # Metadata
    # =====================================================

    def metadata(self):
        """
        Report metadata.
        """

        return {
            "application": APP_NAME,
            "version": APP_VERSION,
            "author": AUTHOR,
            "generated": self.generated.strftime(
                "%Y-%m-%d %H:%M:%S"
            ),
        }

    # =====================================================
    # Executive Summary
    # =====================================================

    def executive_summary(self):
        """
        Executive summary section.
        """

        level = self.results["threat_level"]

        if level == "LOW":

            summary = (
                "Low-risk authentication activity detected. "
                "Continue monitoring."
            )

        elif level == "MEDIUM":

            summary = (
                "Moderate authentication anomalies detected. "
                "Investigation is recommended."
            )

        elif level == "HIGH":

            summary = (
                "High-risk authentication activity detected. "
                "Immediate investigation is recommended."
            )

        else:

            summary = (
                "Critical authentication threat detected. "
                "Immediate incident response is required."
            )

        return summary

    # =====================================================
    # Authentication Statistics
    # =====================================================

    def authentication_statistics(self):
        """
        Authentication statistics.
        """

        return {
            "Failed Logins":
                self.results["failed_logins"],

            "Invalid User Attempts":
                self.results["invalid_user_attempts"],

            "Successful Logins":
                self.results["successful_logins"],

            "Unique IP Addresses":
                self.results["unique_ips"],

            "Threat Level":
                self.results["threat_level"],

            "Risk Score":
                self.results["risk_score"],

            "Top Attacker":
                self.results["top_attacker"],

            "Top Attempts":
                self.results["top_attempts"],
        }
    # =====================================================
    # Detection Summary
    # =====================================================

    def detection_summary(self):
        """
        Return all detections generated by the engine.
        """

        return {
            "Brute Force":
                self.results.get("brute_force_alerts", []),

            "Password Spraying":
                self.results.get("password_spraying_alerts", []),

            "Username Enumeration":
                self.results.get("username_enumeration_alerts", []),

            "Distributed Attack":
                self.results.get("distributed_attack_alerts", []),

            "Suspicious Login":
                self.results.get("suspicious_login_alerts", []),
        }

    # =====================================================
    # MITRE ATT&CK Mapping
    # =====================================================

    def mitre_mapping(self):
        """
        Return unique MITRE ATT&CK techniques.
        """

        techniques = []

        for alerts in self.detection_summary().values():

            for alert in alerts:

                mitre = alert.get("mitre")

                if mitre and mitre not in techniques:
                    techniques.append(mitre)

        return techniques

    # =====================================================
    # Security Recommendations
    # =====================================================

    def recommendations(self):
        """
        Security recommendations.
        """

        recommendations = self.results.get(
            "recommendations",
            []
        )

        if recommendations:
            return recommendations

        level = self.results["threat_level"]

        if level == "LOW":

            return [
                "Continue monitoring authentication activity.",
                "Review failed login attempts periodically.",
            ]

        if level == "MEDIUM":

            return [
                "Investigate repeated authentication failures.",
                "Review SSH authentication logs.",
                "Enable Multi-Factor Authentication where possible.",
            ]

        if level == "HIGH":

            return [
                "Investigate affected systems immediately.",
                "Block malicious IP addresses.",
                "Review privileged accounts.",
                "Enable MFA.",
            ]

        return [
            "Start incident response procedures immediately.",
            "Contain affected systems.",
            "Block attacker infrastructure.",
            "Notify security management.",
            "Preserve forensic evidence.",
        ]

    # =====================================================
    # Evidence
    # =====================================================

    def evidence(self):
        """
        Collect evidence from alerts.
        """

        evidence = []

        for alerts in self.detection_summary().values():

            for alert in alerts:

                if "ip" in alert:

                    evidence.append({
                        "ip": alert["ip"],
                        "severity": alert.get(
                            "severity",
                            "UNKNOWN",
                        ),
                        "mitre": alert.get(
                            "mitre",
                            "-",
                        ),
                    })

        return evidence
    # =====================================================
    # HTML Report
    # =====================================================

    def generate_html(self):
        """
        Generate an HTML report using the Jinja2 template.
        """

        logger.info("Generating HTML report...")

        template = self.environment.get_template("report.html")

        html = template.render(
            metadata=self.metadata(),
            summary=self.executive_summary(),
            statistics=self.authentication_statistics(),
            detections=self.detection_summary(),
            mitre=self.mitre_mapping(),
            recommendations=self.recommendations(),
            evidence=self.evidence(),
        )

        with open(
            HTML_REPORT,
            "w",
            encoding="utf-8",
        ) as report:

            report.write(html)

        logger.info(f"HTML report saved to {HTML_REPORT}")

        return HTML_REPORT

    # =====================================================
    # Text Report
    # =====================================================

    def generate_text(self):
        """
        Generate a professional plain-text SOC report.
        """

        lines = []

        lines.append("=" * 70)
        lines.append(f"{APP_NAME} v{APP_VERSION}")
        lines.append("SOC INCIDENT REPORT")
        lines.append("=" * 70)
        lines.append("")

        meta = self.metadata()

        lines.append(f"Generated : {meta['generated']}")
        lines.append(f"Author    : {meta['author']}")
        lines.append("")

        lines.append("EXECUTIVE SUMMARY")
        lines.append("-" * 70)
        lines.append(self.executive_summary())
        lines.append("")

        lines.append("AUTHENTICATION STATISTICS")
        lines.append("-" * 70)

        for key, value in self.authentication_statistics().items():
            lines.append(f"{key:<25}: {value}")

        lines.append("")

        lines.append("MITRE ATT&CK")
        lines.append("-" * 70)

        mitre = self.mitre_mapping()

        if mitre:

            for technique in mitre:
                lines.append(f"- {technique}")

        else:

            lines.append("No MITRE techniques detected.")

        lines.append("")

        lines.append("SECURITY RECOMMENDATIONS")
        lines.append("-" * 70)

        for item in self.recommendations():
            lines.append(f"- {item}")

        return "\n".join(lines)


# ==========================================================
# Legacy Compatibility Functions
# ==========================================================

def generate_report(results):
    """
    Legacy wrapper for older project code.
    """

    generator = ReportGenerator(results)

    return generator.generate_html()
